import Head from 'next/head'
import axios from 'axios'
import { useState, useEffect } from 'react';

import Nav from '../components/Nav'
import Hero from '../components/Hero'

export default function Home() {

  const [data, setData] = useState({ hits: [] });

  useEffect(() => {
    const fetchData = async () => {
      const result = await axios(
        '/api/json',
      );

      setData(result.data);
    };

    fetchData();
  }, []);
  

  return (
    <>
      <Head>
        <title>Geoloc — Geolocation as a script</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" />
      </Head>

      <Nav />
      <Hero />


      <script defer src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/prism.min.js"></script>
      <script defer src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/plugins/line-numbers/prism-line-numbers.min.js"></script>

    </>
  )
}
