import Head from 'next/head'
import axios from 'axios'
import { useState, useEffect } from 'react';

import Nav from '../components/Nav'
import Hero from '../components/Hero'

export default function Home() {

  const [data, setData] = useState({ hits: [] });

  useEffect(() => {
    const fetchData = async () => {
      const result = await axios(
        '/api/json',
      );

      setData(result.data);
    };

    fetchData();
  }, []);
  

  return (
    <>
      <Head>
        <title>Geoloc — Geolocation as a script</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet" /> 
      </Head>

      <Nav />
      <Hero data={data} />


      <script defer src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/prism.min.js"></script>
      <script defer src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/plugins/line-numbers/prism-line-numbers.min.js"></script>

    </>
  )
}
